Fix status issue

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -61,14 +61,10 @@ jobs:
           echo "Running tester…"
           php -d variables_order=EGPCS "$PWD/vendor/bett-ingenieure/tester/phptester.php"
           
-          status=$?
-          
-          if [ $status -eq 0 ]; then
-            echo "- Tests Passed"
-          else
-            echo "- Tests Failed"
-            exit 1;
-          fi
+          echo "Running tester…"
+          php -d variables_order=EGPCS "$PWD/vendor/bett-ingenieure/tester/phptester.php" || { echo "- Tests Failed"; exit 1; }
+          echo "- Tests Passed"
+
 
 #      - name: Composer auth
 #        run: |
